export const initialValues: { [key: string]: string } = {
  dogName: '',
  dogRace: '',
  dogGender: '',
  dogAge: '',
  dogIsVaccinated: '',
  dogUsesCollar: '',
  ownerName: '',
  locationStreet: '',
  locationComplement: '',
  locationNeighborhood: '',
  locationArea: '',
  locationLatitude: '',
  locationLongitude: '',
  sampleN: '',
  sampleNumber: '',
  sampleDate: '',
  sampleLVC: '',
  sampleIsDead: '',
  sintName: '',
  sintIntensity: '',
  exameName: '',
  exameDate: '',
  exameResult: '',
}